# Configuration for the image registry
# Update these values if you are using a private image registry
imageRegistry:
  host: "ghcr.io"
  imagePullSecret: "syntasso-registry"
  backstageControllerImage:
    name: "syntasso/backstage-controller"
  skeBackstageGeneratorImage:
    name: "syntasso/backstage-controller"
  skeBackstageGeneratorImageVersion: "v0.4.0"

# Configuration for the backstage-controller deployment
backstageController:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  nodeSelector: {}
  tolerations: []
  affinity: {}
