apiVersion: v1
data:
  SKE_BACKSTAGE_GENERATOR_IMG: '{{ .Values.imageRegistry.host }}/{{ .Values.imageRegistry.skeBackstageGeneratorImage.name }}:v0.4.1'
kind: ConfigMap
metadata:
  labels:
    control-plane: kratix-backstage-controller-manager
  name: backstage-controller-config
  namespace: kratix-platform-system
