# Configuration for the image Registry
# Update these values if you are using a custom registry
# If using Syntasso Enterprise defaults, no changes are required
imageRegistry:
  # The host registry to pull the images from Syntasso Enterprise images are hosted on registry.syntasso.io
  # If you are using a custom registry, update this value to your registry host
  host: "registry.syntasso.io"
  imageName: "syntasso/ske-gui"
  imageVersion: "v0.6.1"
  # Name of the image pull secret to use.
  imagePullSecret: "syntasso-registry"
  # imagePullPolicy: IfNotPresent
# Service account to use for the SKE GUI
serviceAccount:
  create: true
  name: "ske-gui-admin"
# RBAC (ClusterRoleBinding) to grant admin permissions to the service account
rbac:
  create: true
# Service configuration
service:
  type: ClusterIP
  port: 80
# Deployment resource configuration
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "100m"
nodeSelector: {}
tolerations: []
affinity: {}
# Ingress configuration
ingress:
  enabled: false # Set to true to enable ingress controller resource
  # -- Additional labels to add to the Ingress resource
  labels: {}
  ingressClassName: ""
  annotations: {}
  # -- Hostname(s) for the Ingress resource
  # Please refer to https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec for more information.
  hosts: []
  # - host: chart-example.local
  #   paths:
  #   - path: /
  #     type: ImplementationSpecific
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
# SKE GUI OIDC configuration, add the following values if you are using OIDC
# oidc:
#  issuerUrl:
#  clientId:
#  clientSecret:
## SKE GUI requests the profile and email scopes by default. More scopes can be added by using the following value.
#  scopes: profile,email
