# Default values for kratix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: null

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# [DEPRECATED] Use additionalResources instead
stateStores:
  - kind: BucketStateStore
    name: default
    namespace: default
    secretRef:
      name: minio-credentials
      # Optional, omit `values` field when the secret creation is managed externally
      values:
        accesskey: bWluaW9hZG1pbg==
        secretkey: bWluaW9hZG1pbg==
    insecure: true
    endpoint: minio.kratix-platform-system.svc.cluster.local
    bucket: kratix

# [DEPRECATED] Use additionalResources instead
destinations: []

# Addition kratix resources to be created, such as GitStateStores, BucketStateStores and Destinations
additionalResources:
#- kind: GitStateStore
#  apiVersion: platform.kratix.io/v1alpha1
#  metadata:
#    name: default
#  spec:
#    secretRef:
#      name: git-credentials
#      namespace: default
#    url: https://172.18.0.2:31333/gitea_admin/kratix
#    branch: main
#- apiVersion: platform.kratix.io/v1alpha1
#  kind: Destination
#  metadata:
#    name: worker-1
#    labels:
#      environment: dev
#  spec:
#    stateStoreRef:
#      name: default
#      kind: GitStateStore
#    path: path/in/statestore
# - apiVersion: v1
#   kind: Secret
#   metadata:
#     name: git-credentials
#     namespace: default
#   type: Opaque
#   data:
#     username: Zm9vCg==
#     password: Zm9vCg==
